// This file is @generated by prost-build.
/// Generic container for any message that is sent to the headless client.
/// Every message sent to the client must be wrapped in this container.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestContainer {
    /// A tag to identify this "to client" message and relate it to the response
    /// in "from client" message. The value 0 means "no identification", i.e. a
    /// specific response is not expected.
    #[prost(uint64, tag = "1")]
    pub tag: u64,
    /// The payload; one of these requests.
    #[prost(
        oneof = "request_container::Content",
        tags = "2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 33, 12, 13, 32, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 34, 26, 27, 28, 29, 30, 31"
    )]
    pub content: ::core::option::Option<request_container::Content>,
}
/// Nested message and enum types in `RequestContainer`.
pub mod request_container {
    /// The payload; one of these requests.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Content {
        #[prost(message, tag = "2")]
        InitializationRequest(super::InitializationRequest),
        #[prost(message, tag = "3")]
        LoginFlowsRequest(super::LoginFlowsRequest),
        #[prost(message, tag = "4")]
        IdentityProvidersRequest(super::IdentityProvidersRequest),
        #[prost(message, tag = "5")]
        LoginUsernamePasswordRequest(super::LoginUsernamePasswordRequest),
        #[prost(message, tag = "6")]
        LoginSsoRequest(super::LoginSsoRequest),
        #[prost(message, tag = "7")]
        RecoveryKeyVerificationRequest(super::RecoveryKeyVerificationRequest),
        #[prost(message, tag = "8")]
        CrossSigningStartRequest(super::CrossSigningStartRequest),
        #[prost(message, tag = "9")]
        CrossSigningMethodSelectedRequest(super::CrossSigningMethodSelectedRequest),
        #[prost(message, tag = "10")]
        CrossSigningConfirmRequest(super::CrossSigningConfirmRequest),
        #[prost(message, tag = "11")]
        VerificationAbortRequest(super::VerificationAbortRequest),
        #[prost(message, tag = "33")]
        GlobalSettingsRequest(super::GlobalSettingsRequest),
        #[prost(message, tag = "12")]
        UserRequest(super::UserRequest),
        #[prost(message, tag = "13")]
        UserSearchRequest(super::UserSearchRequest),
        #[prost(message, tag = "32")]
        UserStatusSetOwnRequest(super::UserStatus),
        #[prost(message, tag = "14")]
        PublicRoomListRequest(super::PublicRoomListRequest),
        #[prost(message, tag = "15")]
        InvitationRequest(super::InvitationRequest),
        #[prost(message, tag = "16")]
        InvitedReply(super::InvitedReply),
        #[prost(message, tag = "17")]
        RoomListRequest(super::RoomListRequest),
        #[prost(message, tag = "18")]
        RoomCreateGroupRequest(super::RoomCreateGroupRequest),
        #[prost(message, tag = "19")]
        RoomCreateDirectRequest(super::RoomCreateDirectRequest),
        #[prost(message, tag = "20")]
        RoomChangeRequest(super::RoomChangeRequest),
        #[prost(message, tag = "21")]
        RoomLeaveRequest(super::RoomLeaveRequest),
        #[prost(message, tag = "22")]
        RoomJoinRequest(super::RoomJoinRequest),
        #[prost(message, tag = "23")]
        RoomKnockRequest(super::RoomKnockRequest),
        #[prost(message, tag = "24")]
        RoomMessagesRequest(super::RoomMessagesRequest),
        #[prost(message, tag = "25")]
        RoomMarkAsReadRequest(super::RoomMarkAsReadRequest),
        #[prost(message, tag = "34")]
        RoomTypingRequest(super::RoomTypingRequest),
        #[prost(message, tag = "26")]
        MessageSendRequest(super::MessageSendRequest),
        #[prost(message, tag = "27")]
        MessageRemoveRequest(super::MessageRemoveRequest),
        #[prost(message, tag = "28")]
        MessageChangeRequest(super::MessageChangeRequest),
        #[prost(message, tag = "29")]
        CreateReactionRequest(super::Reaction),
        #[prost(message, tag = "30")]
        RemoveReactionRequest(super::Reaction),
        #[prost(message, tag = "31")]
        MessageRequest(super::MessageRequest),
    }
}
/// Generic container for any message that is sent from the headless client.
/// Every message sent from the client must be wrapped in this container.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResponseContainer {
    /// A tag to identify which "to client" message this belongs to.
    /// The value 0 means "no identification", i.e. the message does not relate
    /// to a request.
    #[prost(uint64, tag = "1")]
    pub tag: u64,
    /// The payload; one of these requests.
    #[prost(
        oneof = "response_container::Content",
        tags = "2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 31, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30"
    )]
    pub content: ::core::option::Option<response_container::Content>,
}
/// Nested message and enum types in `ResponseContainer`.
pub mod response_container {
    /// The payload; one of these requests.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Content {
        #[prost(message, tag = "2")]
        Error(super::Error),
        #[prost(message, tag = "3")]
        CapabilityEvent(super::CapabilityEvent),
        #[prost(message, tag = "4")]
        StatusUpdate(super::StatusUpdate),
        #[prost(message, tag = "5")]
        LoginFlowsResponse(super::LoginFlowsResponse),
        #[prost(message, tag = "6")]
        LoginSsoResponse(super::LoginSsoResponse),
        #[prost(message, tag = "7")]
        IdentityProvidersResponse(super::IdentityProvidersResponse),
        #[prost(message, tag = "8")]
        VerificationStatusEvent(super::VerificationStatusEvent),
        #[prost(message, tag = "9")]
        CrossSigningPromptEvent(super::CrossSigningPromptEvent),
        #[prost(message, tag = "10")]
        CrossSigningStartResponse(super::CrossSigningStartResponse),
        #[prost(message, tag = "11")]
        CrossSigningStartEvent(super::CrossSigningStartEvent),
        #[prost(message, tag = "12")]
        CrossSigningMethodSelectedEvent(super::CrossSigningMethodSelectedEvent),
        #[prost(message, tag = "13")]
        VerificationEndEvent(super::VerificationEndEvent),
        #[prost(message, tag = "31")]
        GlobalSettingsEvent(super::GlobalSettings),
        #[prost(message, tag = "14")]
        UserResponse(super::User),
        #[prost(message, tag = "15")]
        UserSearchResponse(super::UserSearchResponse),
        #[prost(message, tag = "16")]
        UserChangeEvent(super::UserChangeEvent),
        #[prost(message, tag = "17")]
        PublicRoomListResponse(super::PublicRoomListResponse),
        #[prost(message, tag = "18")]
        InvitedEvent(super::InvitedEvent),
        #[prost(message, tag = "19")]
        RoomListResponse(super::RoomListResponse),
        #[prost(message, tag = "20")]
        RoomCreatedEvent(super::Room),
        #[prost(message, tag = "21")]
        RoomLeftEvent(super::RoomLeftEvent),
        #[prost(message, tag = "22")]
        RoomChangeEvent(super::RoomChangeEvent),
        #[prost(message, tag = "23")]
        MessageSendResponse(super::MessageSendResponse),
        #[prost(message, tag = "24")]
        MessageRemoveEvent(super::MessageRemoveEvent),
        #[prost(message, tag = "25")]
        MessageReceivedEvent(super::Message),
        #[prost(message, tag = "26")]
        MessageChangeEvent(super::MessageChangeEvent),
        #[prost(message, tag = "27")]
        ReactionCreatedEvent(super::Reaction),
        #[prost(message, tag = "28")]
        ReactionRemovedEvent(super::Reaction),
        #[prost(message, tag = "29")]
        MessageResponse(super::Message),
        #[prost(message, tag = "30")]
        MultipartEnd(super::MultipartEnd),
    }
}
/// Generic error occurred in the backend or the headless client.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    /// The type of this error.
    #[prost(enumeration = "error::ErrorType", tag = "1")]
    pub r#type: i32,
    /// An optional string describing details of the error.
    #[prost(string, optional, tag = "2")]
    pub error_string: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `Error`.
pub mod error {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ErrorType {
        /// An error that cannot be described by any of the other values or its
        /// nature is unknown. Using one of the other more specific error type is
        /// preferred.
        Unknown = 0,
        /// When a response was not received in a pre-defined time.
        Timeout = 1,
        /// The error happened with the network connection or failing transport.
        Network = 2,
        /// Whenever the required authorization is missing.
        Authorization = 3,
        /// The requested feature is not implemented for this client. This should
        /// reflect in CapabilityResponse.
        NotImplemented = 4,
        /// The client has not yet been initialized.
        NotInitialized = 5,
        /// A string that should have been formatted as an URL was not a valid
        /// URL.
        InvalidUrl = 6,
        /// The room with the requested ID was not found.
        RoomNotFound = 7,
        /// The verification flow with the requested ID was not found.
        VerificationFlowNotFound = 8,
        /// The given recovery key is invalid.
        InvalidRecoveryKey = 9,
        /// The given user ID is invalid.
        InvalidUserId = 10,
        /// The given message ID is invalid.
        InvalidMessageId = 11,
        /// The message with the given ID was not found.
        MessageNotFound = 12,
        /// An authorization flow was requested but the client is already logged in.
        AlreadyLoggedIn = 13,
        /// An initialization request was made, but the client is already initialized.
        AlreadyInitialized = 14,
        /// The requested reaction was not found.
        ReactionNotFound = 15,
        /// The user does not have sufficient permissions to perform the requested action.
        NotAllowed = 16,
        /// The requested user was not found.
        UserNotFound = 17,
        /// The size limit of a message has been exceeded.
        MessageSizeLimitExceeded = 18,
        /// The size limit of a media upload has been exceeded.
        UploadSizeLimitExceeded = 19,
    }
    impl ErrorType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "Unknown",
                Self::Timeout => "Timeout",
                Self::Network => "Network",
                Self::Authorization => "Authorization",
                Self::NotImplemented => "NotImplemented",
                Self::NotInitialized => "NotInitialized",
                Self::InvalidUrl => "InvalidUrl",
                Self::RoomNotFound => "RoomNotFound",
                Self::VerificationFlowNotFound => "VerificationFlowNotFound",
                Self::InvalidRecoveryKey => "InvalidRecoveryKey",
                Self::InvalidUserId => "InvalidUserId",
                Self::InvalidMessageId => "InvalidMessageId",
                Self::MessageNotFound => "MessageNotFound",
                Self::AlreadyLoggedIn => "AlreadyLoggedIn",
                Self::AlreadyInitialized => "AlreadyInitialized",
                Self::ReactionNotFound => "ReactionNotFound",
                Self::NotAllowed => "NotAllowed",
                Self::UserNotFound => "UserNotFound",
                Self::MessageSizeLimitExceeded => "MessageSizeLimitExceeded",
                Self::UploadSizeLimitExceeded => "UploadSizeLimitExceeded",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Unknown" => Some(Self::Unknown),
                "Timeout" => Some(Self::Timeout),
                "Network" => Some(Self::Network),
                "Authorization" => Some(Self::Authorization),
                "NotImplemented" => Some(Self::NotImplemented),
                "NotInitialized" => Some(Self::NotInitialized),
                "InvalidUrl" => Some(Self::InvalidUrl),
                "RoomNotFound" => Some(Self::RoomNotFound),
                "VerificationFlowNotFound" => Some(Self::VerificationFlowNotFound),
                "InvalidRecoveryKey" => Some(Self::InvalidRecoveryKey),
                "InvalidUserId" => Some(Self::InvalidUserId),
                "InvalidMessageId" => Some(Self::InvalidMessageId),
                "MessageNotFound" => Some(Self::MessageNotFound),
                "AlreadyLoggedIn" => Some(Self::AlreadyLoggedIn),
                "AlreadyInitialized" => Some(Self::AlreadyInitialized),
                "ReactionNotFound" => Some(Self::ReactionNotFound),
                "NotAllowed" => Some(Self::NotAllowed),
                "UserNotFound" => Some(Self::UserNotFound),
                "MessageSizeLimitExceeded" => Some(Self::MessageSizeLimitExceeded),
                "UploadSizeLimitExceeded" => Some(Self::UploadSizeLimitExceeded),
                _ => None,
            }
        }
    }
}
/// Object used to mark a multi-part answer as complete.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MultipartEnd {}
/// Initializes a client and establishes a connection to the specified backend.
/// A StatusUpdate is returned when the connection was successful.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
#[prost(skip_debug)]
pub struct InitializationRequest {
    /// The URL of the backend to which a connection should be established.
    #[prost(string, tag = "1")]
    pub backend_url: ::prost::alloc::string::String,
    /// Path to a readable and writable folder in the system which serves as a
    /// root path for mutual data, like images.
    #[prost(string, tag = "2")]
    pub data_root_path: ::prost::alloc::string::String,
    /// Secret for access to the client's secret storage (i.e. database).
    #[prost(string, tag = "3")]
    pub persistent_storage_secret: ::prost::alloc::string::String,
    /// Secret the client can use for encryption and decryption of arbitrary
    /// data.
    #[prost(string, tag = "4")]
    pub encryption_secret: ::prost::alloc::string::String,
    /// The display name of this device.
    #[prost(string, tag = "5")]
    pub device_display_name: ::prost::alloc::string::String,
}
/// Send when the verification status or related information has changed. Must
/// be sent at least once if CapabilityResponse.clientVerification is true. If
/// that is not true, it must not be sent at all.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerificationStatusEvent {
    /// Whether this client/device is verified.
    #[prost(bool, tag = "1")]
    pub is_verified: bool,
    /// Whether this client/device can verify itself by sending a recovery key
    /// via RecoveryKeyVerificationRequest.
    #[prost(bool, tag = "2")]
    pub is_recovery_key_verification_available: bool,
    /// Whether an unverified device can currently be verified via
    /// cross-signing.
    #[prost(bool, tag = "3")]
    pub is_cross_signing_available: bool,
}
/// Try to verify this device with the givenrecovery key.
/// Expects a VerificationEndEvent afterwards.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
#[prost(skip_debug)]
pub struct RecoveryKeyVerificationRequest {
    #[prost(string, tag = "1")]
    pub recovery_key: ::prost::alloc::string::String,
}
/// Another device wants to verify this one.
/// The client is expected to send either a CrossSigningStartRequest in order to
/// accept the prompt, or a VerificationAbortRequest to reject it.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CrossSigningPromptEvent {
    /// Identifier for the verification flow id.
    #[prost(string, tag = "1")]
    pub verification_flow_id: ::prost::alloc::string::String,
}
/// The client declares it likes to start a cross signing verification process.
/// A CrossSigningStartResponse is expected to be received next.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CrossSigningStartRequest {
    /// Id of the flow if responding to a CrossSigningPromptEvent. If such did
    /// not happen, this field must be omitted.
    #[prost(string, optional, tag = "1")]
    pub verification_flow_id: ::core::option::Option<::prost::alloc::string::String>,
    /// All cross signing methods this client supports. It must not be empty.
    #[prost(enumeration = "CrossSigningMethod", repeated, tag = "2")]
    pub supported_methods: ::prost::alloc::vec::Vec<i32>,
}
/// Confirms a new cross signing flow was started.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CrossSigningStartResponse {
    /// The ID  of the newly created verification flow.
    #[prost(string, tag = "1")]
    pub verification_flow_id: ::prost::alloc::string::String,
}
/// The backend declares it the cross signing verification flow has started.
/// The headless client either expects a CrossSigningMethodSelectRequest next or
/// will send a CrossSigningMethodSelectedEvent when another client has selected
/// a method sooner.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CrossSigningStartEvent {
    #[prost(string, tag = "1")]
    pub verification_flow_id: ::prost::alloc::string::String,
    /// List of cross signing methods that are available among all clients and
    /// the backend. One of this must be chosen to proceed. Must not be empty.
    #[prost(enumeration = "CrossSigningMethod", repeated, tag = "2")]
    pub available_methods: ::prost::alloc::vec::Vec<i32>,
}
/// Send in response to a CrossSigningStartEvent to select the cross signing
/// method. A CrossSigningMethodSelectedEvent is expected in return.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CrossSigningMethodSelectedRequest {
    #[prost(string, tag = "1")]
    pub verification_flow_id: ::prost::alloc::string::String,
    /// The selected method. Must be one of those received in the according
    /// CrossSigningStartEvent.
    #[prost(enumeration = "CrossSigningMethod", tag = "2")]
    pub selected_method: i32,
}
/// Propagates the method selected for the cross signing process. Must be
/// followed by either a CrossSigningAcceptRequest or a
/// VerificationAbortRequest.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
#[prost(skip_debug)]
pub struct CrossSigningMethodSelectedEvent {
    #[prost(string, tag = "1")]
    pub verification_flow_id: ::prost::alloc::string::String,
    #[prost(enumeration = "CrossSigningMethod", tag = "2")]
    pub selected_method: i32,
    /// Code to match for the verification. Depends on the selected method.
    #[prost(
        oneof = "cross_signing_method_selected_event::VerificationCode",
        tags = "3, 4"
    )]
    pub verification_code: ::core::option::Option<
        cross_signing_method_selected_event::VerificationCode,
    >,
}
/// Nested message and enum types in `CrossSigningMethodSelectedEvent`.
pub mod cross_signing_method_selected_event {
    /// Code to match for the verification. Depends on the selected method.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    #[prost(skip_debug)]
    pub enum VerificationCode {
        /// A simple string for the SasString method.
        #[prost(string, tag = "3")]
        StringCode(::prost::alloc::string::String),
        /// A sequence of symbols for the SasSymbol method.
        #[prost(message, tag = "4")]
        Symbols(super::VerificationSymbolSequence),
    }
}
/// Accepts the verification. Must be followed by VerificationEndEvent.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CrossSigningConfirmRequest {
    #[prost(string, tag = "1")]
    pub verification_flow_id: ::prost::alloc::string::String,
}
/// Sequence of VerificationSymbol.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerificationSymbolSequence {
    #[prost(message, repeated, tag = "1")]
    pub symbols: ::prost::alloc::vec::Vec<VerificationSymbol>,
}
/// A single symbol for the SasSymbol verification method.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerificationSymbol {
    /// The symbol itself (e.g. emoji).
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    /// Optional description to be shown with the symbol.
    #[prost(string, optional, tag = "2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
/// This client wants to abort the verification process. Is expected to be
/// followed by a VerificationEndEvent.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerificationAbortRequest {
    #[prost(string, tag = "1")]
    pub verification_flow_id: ::prost::alloc::string::String,
}
/// Send when the verification process has ended, because it was either
/// successful, or cancelled or erroneous.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerificationEndEvent {
    /// Id of the verification flow. Might be omitted if this is a direct final
    /// response to the process such that no id was known before.
    #[prost(string, optional, tag = "1")]
    pub verification_flow_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(oneof = "verification_end_event::Result", tags = "2, 3")]
    pub result: ::core::option::Option<verification_end_event::Result>,
}
/// Nested message and enum types in `VerificationEndEvent`.
pub mod verification_end_event {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        /// Whether the verification has ended successfully or was aborted.
        #[prost(bool, tag = "2")]
        Successful(bool),
        /// Verification has ended with an error; this is an error message.
        #[prost(string, tag = "3")]
        Error(::prost::alloc::string::String),
    }
}
/// Request to retrieve the login flows supported by the backend.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginFlowsRequest {}
/// Returns the login flows supported by the backend.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginFlowsResponse {
    /// The supported login flows.
    #[prost(enumeration = "login_flows_response::LoginFlow", repeated, tag = "2")]
    pub login_flows: ::prost::alloc::vec::Vec<i32>,
}
/// Nested message and enum types in `LoginFlowsResponse`.
pub mod login_flows_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum LoginFlow {
        /// If the backend supports username and password authentication.
        UsernamePassword = 0,
        /// If the backend supports single sign-on authentication.
        Sso = 1,
    }
    impl LoginFlow {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::UsernamePassword => "UsernamePassword",
                Self::Sso => "SSO",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UsernamePassword" => Some(Self::UsernamePassword),
                "SSO" => Some(Self::Sso),
                _ => None,
            }
        }
    }
}
/// Request to log in to the client using username and password.
/// Use LoginFlowsRequest to ensure that the backend supports this authentication
/// method. A StatusUpdate is returned when the login request was successful.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
#[prost(skip_debug)]
pub struct LoginUsernamePasswordRequest {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
/// Request to log in to the client using single sign-on.
/// Use LoginFlowsRequest to ensure that the backend supports this authentication
/// method.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginSsoRequest {
    /// The identity provider to be used for login.
    /// Use IdentityProviderRequest to retrieve the available identity providers.
    #[prost(string, optional, tag = "1")]
    pub identity_provider: ::core::option::Option<::prost::alloc::string::String>,
}
/// Confirms the single sign-on authentication was initiated.
/// A StatusUpdate is returned when the login request was successful and the
/// access token was retrieved.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginSsoResponse {
    /// A url that must be opened in a web browser to continue the login process.
    #[prost(string, tag = "1")]
    pub login_url: ::prost::alloc::string::String,
}
/// Request to retrieve the available identity providers for single sing-on
/// authentication.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IdentityProvidersRequest {}
/// Returns the available identity providers.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IdentityProvidersResponse {
    /// The ID of the available identity providers.
    /// Use one of the returned IDs inside the SSOLoginRequest.
    #[prost(string, repeated, tag = "1")]
    pub identity_providers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Notifies about changes in the connection state between headless client and
/// backend.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusUpdate {
    /// The current connection status.
    #[prost(enumeration = "status_update::StatusCode", tag = "1")]
    pub code: i32,
}
/// Nested message and enum types in `StatusUpdate`.
pub mod status_update {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum StatusCode {
        /// The user has been logged out and is not logged in any longer. The
        /// user can attempt to login again.
        LoggedOut = 0,
        /// The server is connected, but the client is not authorized yet.
        Connected = 1,
        /// The server is connected and the client is authorized.
        LoggedIn = 2,
        /// The headless client has no network connection to the backend. Any
        /// attempt to login or send requests will be responded with errors.
        NetworkUnavailable = 3,
        /// The session has been invalidated (usually by another client). Other
        /// than that, it has the same semantics as "LoggedOut".
        SessionInvalid = 4,
    }
    impl StatusCode {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::LoggedOut => "LoggedOut",
                Self::Connected => "Connected",
                Self::LoggedIn => "LoggedIn",
                Self::NetworkUnavailable => "NetworkUnavailable",
                Self::SessionInvalid => "SessionInvalid",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "LoggedOut" => Some(Self::LoggedOut),
                "Connected" => Some(Self::Connected),
                "LoggedIn" => Some(Self::LoggedIn),
                "NetworkUnavailable" => Some(Self::NetworkUnavailable),
                "SessionInvalid" => Some(Self::SessionInvalid),
                _ => None,
            }
        }
    }
}
/// Request the headless client to send the capabilities of the backend.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CapabilityRequest {}
/// The capabilities (supported features) of the backend.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CapabilityEvent {
    /// The backend supports direct communication between two users.
    #[prost(bool, tag = "1")]
    pub direct_rooms: bool,
    /// The backend supports chat rooms between multiple users.
    #[prost(bool, tag = "2")]
    pub group_rooms: bool,
    /// The backend supports creation of sub threads inside a chat room.
    #[prost(bool, tag = "3")]
    pub sub_threads: bool,
    /// The backend supports searching for people known to the chat system.
    #[prost(bool, tag = "5")]
    pub user_search: bool,
    /// The backend supports inviting users to rooms.
    #[prost(bool, tag = "6")]
    pub invitations: bool,
    /// The backend supports spaces as logical groups of rooms.
    #[prost(bool, tag = "7")]
    pub spaces: bool,
    /// The protocol has a verification process for clients. This does neither
    /// mean that the backend actually supports it, nor that the client
    /// actually requires verification.
    #[prost(bool, tag = "8")]
    pub client_verification: bool,
    /// The backend supports a presence state for users.
    #[prost(bool, tag = "9")]
    pub user_presence: bool,
    /// List of MIME types that can be send via the backend.
    #[prost(string, repeated, tag = "4")]
    pub mime_types: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The maximum allowed size in bytes of media files that are uploaded.
    #[prost(uint64, tag = "10")]
    pub media_size_limit: u64,
}
/// A message sent to a room.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    /// Id of the room this message is sent to.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// Unique string identifying the message.
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    /// Id of the sender, which might be a user or the room itself in case of
    /// room messages.
    #[prost(string, tag = "3")]
    pub sender_id: ::prost::alloc::string::String,
    /// Creation time of the message in milliseconds from 01.01.1970 00:00 UTC.
    #[prost(uint64, tag = "4")]
    pub timestamp: u64,
    /// The original message this relates to, e.g. when answering to a specific
    /// message.
    #[prost(string, optional, tag = "5")]
    pub related_message_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Whether this message is pinned, i.e. prominently shown in the room.
    #[prost(bool, tag = "6")]
    pub is_pinned: bool,
    /// Whether this message is considered to be encrypted - which means that the latest
    /// decryption attempt failed. When this field is true, server implementations should
    /// leave the `content` empty and clients should ignore the value of `content`.
    #[prost(bool, tag = "7")]
    pub is_encrypted: bool,
    /// Contains all reactions to this message.
    #[prost(message, repeated, tag = "8")]
    pub reactions: ::prost::alloc::vec::Vec<Reaction>,
    /// Ids of users that have been mentioned in this message.
    #[prost(string, repeated, tag = "13")]
    pub mentioned_user_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The actual content of the message.
    /// Not specifying the content is not allowed.
    #[prost(oneof = "message::Content", tags = "9, 11, 12")]
    pub content: ::core::option::Option<message::Content>,
}
/// Nested message and enum types in `Message`.
pub mod message {
    /// The actual content of the message.
    /// Not specifying the content is not allowed.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Content {
        /// The message content if it is a plain text message.
        #[prost(message, tag = "9")]
        Text(super::MessageContentText),
        /// The message content if it is a file.
        #[prost(message, tag = "11")]
        File(super::MessageContentFile),
        /// The message content if it is a membership change.
        #[prost(message, tag = "12")]
        MembershipChange(super::MessageContentMembershipChange),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
#[prost(skip_debug)]
pub struct MessageContentText {
    /// The actual plain text content of the message.
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageContentFile {
    /// The relative path to the file starting from
    /// the `InitializationRequest::dataRoorPath`.
    #[prost(string, tag = "1")]
    pub file_path: ::prost::alloc::string::String,
    /// The name of the file, if available.
    #[prost(string, optional, tag = "2")]
    pub file_name: ::core::option::Option<::prost::alloc::string::String>,
}
/// The message content, if it is a message about a change in membership,
/// for example, when a user has left or entered the room.
/// The affected user may differ from the sender and is listed separately here.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageContentMembershipChange {
    /// The change of membership status.
    #[prost(
        enumeration = "message_content_membership_change::MembershipChange",
        tag = "1"
    )]
    pub change: i32,
    /// The ID of the user the change applies to
    #[prost(string, tag = "2")]
    pub affected_user_id: ::prost::alloc::string::String,
}
/// Nested message and enum types in `MessageContentMembershipChange`.
pub mod message_content_membership_change {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MembershipChange {
        Joined = 0,
        Left = 1,
        Invited = 2,
        Knocked = 3,
        Banned = 4,
        Unbanned = 5,
        Kicked = 6,
    }
    impl MembershipChange {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Joined => "Joined",
                Self::Left => "Left",
                Self::Invited => "Invited",
                Self::Knocked => "Knocked",
                Self::Banned => "Banned",
                Self::Unbanned => "Unbanned",
                Self::Kicked => "Kicked",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Joined" => Some(Self::Joined),
                "Left" => Some(Self::Left),
                "Invited" => Some(Self::Invited),
                "Knocked" => Some(Self::Knocked),
                "Banned" => Some(Self::Banned),
                "Unbanned" => Some(Self::Unbanned),
                "Kicked" => Some(Self::Kicked),
                _ => None,
            }
        }
    }
}
/// Request a single specific message.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageRequest {
    /// Id of the room this message is from.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// Id of the message itself.
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
}
/// Request to send a new message to a room.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageSendRequest {
    /// Id of the room this message is sent to.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// The original message this relates to, e.g. when answering to a specific
    /// message.
    #[prost(string, optional, tag = "2")]
    pub related_message_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Ids of users that have been mentioned in this message.
    #[prost(string, repeated, tag = "6")]
    pub mentioned_user_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The actual content of the message.
    /// This field must not be empty.
    #[prost(oneof = "message_send_request::Content", tags = "3, 5")]
    pub content: ::core::option::Option<message_send_request::Content>,
}
/// Nested message and enum types in `MessageSendRequest`.
pub mod message_send_request {
    /// The actual content of the message.
    /// This field must not be empty.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Content {
        /// The message content if it is a plain text message.
        #[prost(message, tag = "3")]
        Text(super::MessageContentText),
        /// The message content if it is a file.
        #[prost(message, tag = "5")]
        File(super::MessageContentFile),
    }
}
/// Confirms that a message has been sent.
/// A MessageReceivedEvent will not be created for messages that have been sent
/// via this client.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageSendResponse {
    /// Unique id to identify the message (e.g. for later modification).
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
/// Request changes to the content of an existing chat message.
/// A MessageChangeEvent or an Error is expected to be received afterwards.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageChangeRequest {
    /// The ID of the room the message is located.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// Id of the chat message that shall be changed.
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    /// Whether mentionedUserIds should be updated.
    #[prost(bool, tag = "7")]
    pub has_mentioned_user_ids_changed: bool,
    /// Ids of users that have been mentioned in this message. The value of this
    /// field is only defined when hasMentionedUserIdsChanged is true.
    #[prost(string, repeated, tag = "8")]
    pub mentioned_user_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The new content of the message.
    /// This field must not be empty. In order to remove a message, a
    /// MessageRemoveRequest must be made.
    #[prost(oneof = "message_change_request::Content", tags = "4, 6")]
    pub content: ::core::option::Option<message_change_request::Content>,
}
/// Nested message and enum types in `MessageChangeRequest`.
pub mod message_change_request {
    /// The new content of the message.
    /// This field must not be empty. In order to remove a message, a
    /// MessageRemoveRequest must be made.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Content {
        /// The message content if it is a plain text message.
        #[prost(message, tag = "4")]
        Text(super::MessageContentText),
        /// The message content if it is a file.
        #[prost(message, tag = "6")]
        File(super::MessageContentFile),
    }
}
/// Notifies about changes in a single Message.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageChangeEvent {
    /// The ID of the room the message is located.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// Id of the changed message. Must be a valid id of an already existing
    /// message.
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    /// Whether the message is pinned (i.e. shown prominently in the room) or
    /// not. Shall only be set if it has changed.
    #[prost(bool, optional, tag = "3")]
    pub is_pinned: ::core::option::Option<bool>,
    /// Whether the message is encrypted or not. Shall only be set if it has
    /// changed. If it changes, the content should usually change as well.
    #[prost(bool, optional, tag = "4")]
    pub is_encrypted: ::core::option::Option<bool>,
    /// Whether the field mentionedUserIds has changed.
    #[prost(bool, tag = "8")]
    pub has_mentioned_user_ids_changed: bool,
    /// Ids of users that have been mentioned in this message. The value of this
    /// field is only defined when hasMentionedUserIdsChanged is true.
    #[prost(string, repeated, tag = "9")]
    pub mentioned_user_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// If set, a new content for the message.
    #[prost(oneof = "message_change_event::Content", tags = "5, 7, 10")]
    pub content: ::core::option::Option<message_change_event::Content>,
}
/// Nested message and enum types in `MessageChangeEvent`.
pub mod message_change_event {
    /// If set, a new content for the message.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Content {
        /// The message content if it is a plain text message.
        #[prost(message, tag = "5")]
        Text(super::MessageContentText),
        /// The message content if it is a file.
        #[prost(message, tag = "7")]
        File(super::MessageContentFile),
        /// The message content if it is a membership change.
        #[prost(message, tag = "10")]
        MembershipChange(super::MessageContentMembershipChange),
    }
}
/// Request the backend to retract and delete an existing message.
/// Must result in an Error or MessageRemoveEvent.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageRemoveRequest {
    /// The ID of the room the message is located.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// Id of the chat message that shall be removed.
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
}
/// Event notifying that a message has been retracted and removed.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageRemoveEvent {
    /// The ID of the room the message is located.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// Id of the removed message.
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    /// Optional reason for the removal
    #[prost(string, optional, tag = "3")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    /// The origin the the removal event
    #[prost(enumeration = "EventOrigin", tag = "4")]
    pub origin: i32,
}
/// Request a list of rooms.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomListRequest {
    /// Whether the resulting list shall include room which the user is a member
    /// of.
    #[prost(bool, tag = "1")]
    pub include_joined: bool,
    /// Whether the resulting list shall include room which the user is not a
    /// member of.
    #[prost(bool, tag = "2")]
    pub include_unjoined: bool,
}
/// Response to a RoomListResponse.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomListResponse {
    /// The requested list of rooms.
    #[prost(message, repeated, tag = "1")]
    pub room_list: ::prost::alloc::vec::Vec<Room>,
}
/// Describes a single user entity.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct User {
    /// Unique string which identifies the user.
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// Optional nice name to display instead of the userId.
    #[prost(string, optional, tag = "2")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
    /// The relative path from the `dataRootPath` directory to the downloaded user
    /// avatar, if any is available.
    #[prost(string, optional, tag = "4")]
    pub avatar_path: ::core::option::Option<::prost::alloc::string::String>,
    /// The status of the user.
    #[prost(message, optional, tag = "5")]
    pub status: ::core::option::Option<UserStatus>,
}
/// Request to fetch the information of a single user.
/// An UserResponse is expected next.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserRequest {
    /// The ID of the user to fetch information from.
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserChangeEvent {
    /// The ID of the user this change occurs.
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// New status of the user. If not set the status did not
    /// change. May only be set when userPresence capability is set.
    #[prost(message, optional, tag = "2")]
    pub status: ::core::option::Option<UserStatus>,
    /// New display name for the user, if set.
    #[prost(string, optional, tag = "3")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
    /// New path to a changed avatar image, relative to the dataRootPath of the
    /// client. If empty, the avatar has been removed. If not set, it remains
    /// unchanged.
    #[prost(string, optional, tag = "4")]
    pub avatar_path: ::core::option::Option<::prost::alloc::string::String>,
}
/// A space describes a logical group of chat rooms.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Space {
    /// Unique identifier of the space.
    #[prost(string, tag = "1")]
    pub space_id: ::prost::alloc::string::String,
    /// User-friendly display name for the space.
    #[prost(string, optional, tag = "2")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
}
/// Request global settings; GlobalSettingsEvent is expected in return, if
/// StatusUpdate.statusCode is LoggedIn, or an error if not logged in.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GlobalSettingsRequest {}
/// Response to GlobalSettingsRequest (with tag) or when the settings have
/// changed on the backend (without tag).
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GlobalSettings {
    /// The global settings for notification incoming messages.
    #[prost(enumeration = "NotificationSetting", tag = "1")]
    pub notification_setting: i32,
}
/// Room-specific settings
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomSettings {
    /// The room-specific settings for notification incoming messages which
    /// overrides the global setting. If not set, the global settings will be
    /// used.
    #[prost(enumeration = "NotificationSetting", optional, tag = "1")]
    pub notification_setting: ::core::option::Option<i32>,
}
/// Describes a room entity. This might be a room with several users or just a
/// direct chat between two.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Room {
    /// Unique string identifying the room.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// Nice name to display instead of the roomId.
    #[prost(string, optional, tag = "2")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Ids of all users in this room with their current state, including our own
    /// user.
    #[prost(map = "string, enumeration(UserRoomState)", tag = "3")]
    pub user_id_list: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    /// Ids of the spaces this room belongs to.
    /// This is only to be set if the backend supports the spaces capability and
    /// the room actually belongs to at least one space.
    #[prost(string, repeated, tag = "4")]
    pub space_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Number of unread messages and notifications in this room.
    #[prost(uint32, tag = "5")]
    pub unread_count: u32,
    /// If the room is a direct room or group room.
    #[prost(bool, tag = "6")]
    pub is_direct: bool,
    /// The join rule of this room.
    #[prost(enumeration = "RoomJoinRule", tag = "7")]
    pub join_rule: i32,
    /// The permissions this client has in the room.
    #[prost(message, optional, tag = "8")]
    pub permissions: ::core::option::Option<RoomPermissions>,
    /// Timestamp in milliseconds since January 1, 1970, 00:00 UTC of the last
    /// send or received message. Unset if no activity has occurred yet.
    #[prost(uint64, optional, tag = "9")]
    pub latest_message_timestamp: ::core::option::Option<u64>,
    /// The relative path from the `dataRootPath` directory to the downloaded room
    /// avatar, if any is available.
    #[prost(string, optional, tag = "10")]
    pub avatar_path: ::core::option::Option<::prost::alloc::string::String>,
    /// Whether the room is tagged as favorite by the user.
    #[prost(bool, tag = "11")]
    pub is_favorite: bool,
    /// Room-specific settings
    #[prost(message, optional, tag = "12")]
    pub room_settings: ::core::option::Option<RoomSettings>,
}
/// Defines single points of authorization for a room that may or may not be done
/// by this client's user.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomPermissions {
    /// The user can edit basic information of the room, such as the name or
    /// topic.
    #[prost(bool, tag = "1")]
    pub can_edit: bool,
    /// The user can invite other users to the room.
    #[prost(bool, tag = "2")]
    pub can_invite: bool,
    /// The user can kick other users out of the room.
    #[prost(bool, tag = "3")]
    pub can_kick: bool,
    /// The user can ban other users from the room.
    #[prost(bool, tag = "4")]
    pub can_ban: bool,
}
/// Informs the client about changes in a single room.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomChangeEvent {
    /// The id of the room this change occurs.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// If the userIdList has changed with this event.
    /// If false, the userIdList has not changed and only contains a
    /// default value that should not be used.
    #[prost(bool, tag = "6")]
    pub has_user_id_list_changed: bool,
    /// If the typingUserIdList has changed with this event.
    /// If false, the typingUserIdList has not changed and only contains a
    /// default value that should not be used.
    #[prost(bool, tag = "7")]
    pub has_typing_user_id_list_changed: bool,
    /// User ids and their new state if they have changed. Users with unchanged
    /// state must not appear in this list.
    #[prost(map = "string, enumeration(UserRoomState)", tag = "2")]
    pub user_id_list: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    /// List of ids of all users which are currently typing.
    #[prost(string, repeated, tag = "3")]
    pub typing_user_id_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Updated display name of the room, if it has changed.
    #[prost(string, optional, tag = "4")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Updated number of unread messages and notifications in this room, if it
    /// has changed.
    #[prost(uint32, optional, tag = "5")]
    pub unread_count: ::core::option::Option<u32>,
    /// Updated join rule of the room, if it has changed.
    #[prost(enumeration = "RoomJoinRule", optional, tag = "8")]
    pub join_rule: ::core::option::Option<i32>,
    /// Whether the room is a direct room or not. Should only be set if the value
    /// has changed.
    #[prost(bool, optional, tag = "9")]
    pub is_direct: ::core::option::Option<bool>,
    /// The permissions this client has in the room. Should only be set if the
    /// value has changed.
    #[prost(message, optional, tag = "10")]
    pub permissions: ::core::option::Option<RoomPermissions>,
    /// The relative path from the `dataRootPath` directory to the downloaded room
    /// avatar, if it has changed.
    #[prost(string, optional, tag = "11")]
    pub avatar_path: ::core::option::Option<::prost::alloc::string::String>,
    /// If set, the favorite state has changed to the given value.
    #[prost(bool, optional, tag = "12")]
    pub is_favorite: ::core::option::Option<bool>,
    /// Set when the room-specific settings have changed. The message must
    /// contain all of the room settings, even those which have not changed.
    #[prost(message, optional, tag = "13")]
    pub room_settings: ::core::option::Option<RoomSettings>,
}
/// Notify the client that messages and notifications in this room have been
/// read by the user.
/// Expects a RoomChangeEvent with unreadCount = 0 in return.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomMarkAsReadRequest {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
}
/// Activate typing notice for the current user in the specified room.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomTypingRequest {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
}
/// Describes a reaction to a message, e.g. attaching an emoji to it.
/// A reaction is identified by messageId and reaction combined.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Reaction {
    /// The room where the message is located.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// The message the reaction is for.
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    /// The reaction (e.g. emoji).
    #[prost(string, tag = "3")]
    pub reaction: ::prost::alloc::string::String,
    /// The user that created the reaction.
    /// This field can be omitted when creating a new reaction.
    #[prost(string, optional, tag = "4")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// Request multiple consecutive messages of a room.
/// The request should usually be used paginated, i.e. with a reasonable limit
/// set.
/// The response is expected to be a multi-part response of MessageReceivedEvent's.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomMessagesRequest {
    /// Id of the room for which messages shall be fetched.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// Request messages in chronological or anti-chronological order. If omitted,
    /// the result is expected in anti-chronological (backward) order.
    #[prost(enumeration = "MessagesOrder", optional, tag = "2")]
    pub order: ::core::option::Option<i32>,
    /// The result must start at the message that is the immediate successor
    /// to the one specified by this id - if available. If this field is not set,
    /// the result must begin at the latest message if `order=backward` and at
    /// the oldest known message if `order=forward`.
    #[prost(string, optional, tag = "3")]
    pub from_message_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Maximum number of messages that should be contained in the resulting
    /// list. If the toMessageId field is set as well, the resulting list must
    /// be limited at whatever applies first - the toMessageId or the limit.
    #[prost(uint32, optional, tag = "4")]
    pub limit: ::core::option::Option<u32>,
}
/// Describes a request to search for known users, i.e. accounts registered to
/// the chat backend. Only available if the capability userSearch is available.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserSearchRequest {
    /// The search query string.
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    /// The maximum number of search results that shall be returned.
    #[prost(uint32, tag = "2")]
    pub limit: u32,
}
/// Response to a UserSearchRequest.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserSearchResponse {
    /// List of users matching the search query.
    #[prost(message, repeated, tag = "1")]
    pub user_list: ::prost::alloc::vec::Vec<User>,
}
/// Describes the presence status of a user, e.g. used for setting the own state
/// by using the according request.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserStatus {
    /// The current state of the user. The value "Unknown" is n/a.
    #[prost(enumeration = "PresenceState", tag = "1")]
    pub state: i32,
    /// Optional free-text status message that other users can see.
    #[prost(string, optional, tag = "2")]
    pub status_message: ::core::option::Option<::prost::alloc::string::String>,
}
/// Issue an invite to one or more users to join a chat room.
/// This is only available if the invitations capability is supported.
/// Sending an InvitationRequest without an invitee is insufficient.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvitationRequest {
    /// The id of the room the users are invited to.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// The list of ids of users that shall be invited to the room.
    /// Must contain at least one user.
    #[prost(string, repeated, tag = "2")]
    pub invitees: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Free text to display to the invitees together with the invitation.
    #[prost(string, optional, tag = "3")]
    pub invitation_text: ::core::option::Option<::prost::alloc::string::String>,
}
/// Received when another user invites this account to a chat room.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvitedEvent {
    /// The id of the room this client is invited to.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// Display name of the room.
    #[prost(string, optional, tag = "2")]
    pub room_display_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Free text to display to the client together with the invitation.
    #[prost(string, optional, tag = "3")]
    pub invitation_text: ::core::option::Option<::prost::alloc::string::String>,
}
/// The client's answer to an Invited.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvitedReply {
    /// Id of the room to where the client has been invited.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// Whether the invitation is accepted or not. If it is, an update for the
    /// room list is expected.
    #[prost(bool, tag = "2")]
    pub accepted: bool,
}
/// Request to create a new room that multiple users can join.
/// Expects a RoomCreatedEvent next.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomCreateGroupRequest {
    /// Optional nice name to display instead of the roomId.
    /// An empty string can be interpreted as no displayName set.
    #[prost(string, optional, tag = "1")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
    /// The join rule of the new room.
    #[prost(enumeration = "RoomJoinRule", tag = "2")]
    pub join_rule: i32,
    /// The IDs of the users who should be invited to the new group room.
    #[prost(string, repeated, tag = "3")]
    pub invitees: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// If set, a path to an image file relative to
    /// InitializationRequest.dataRootPath that shall be used as the room
    /// avatar. The image must remain at that path until a RoomChangeEvent
    /// changes it. After that, the callee is free to remove the file.
    /// The caller must ensure that the path is correct and that an image file is
    /// actually at that path.
    /// An empty string is not allowed; the field must not be set at all in that
    /// case.
    #[prost(string, optional, tag = "4")]
    pub avatar_path: ::core::option::Option<::prost::alloc::string::String>,
}
/// Request to create a new room that only one user can join.
/// Expects a RoomCreatedEvent next.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomCreateDirectRequest {
    /// Optional nice name to display instead of the roomId or the other person's
    /// name. An empty string can be interpreted as no displayName set.
    #[prost(string, optional, tag = "1")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
    /// The user who should be invited to the new direct room.
    #[prost(string, tag = "2")]
    pub invitee: ::prost::alloc::string::String,
    /// If set, a path to an image file relative to
    /// InitializationRequest.dataRootPath that shall be used as the room
    /// avatar. The image must remain at that path until a RoomChangeEvent
    /// changes it. After that, the callee is free to remove the file.
    /// The caller must ensure that the path is correct and that an image file is
    /// actually at that path.
    /// An empty string is not allowed; the field must not be set at all in that
    /// case.
    #[prost(string, optional, tag = "3")]
    pub avatar_path: ::core::option::Option<::prost::alloc::string::String>,
}
/// Request to edit an already existing room.
/// Expects a RoomChangeEvent next.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomChangeRequest {
    /// The ID of the room to be edited.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// A new display name if it should be changed.
    #[prost(string, optional, tag = "2")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
    /// New rule of how this room can be joined.
    #[prost(enumeration = "RoomJoinRule", optional, tag = "3")]
    pub join_rule: ::core::option::Option<i32>,
    /// If set flag/unflag the room as favorite.
    #[prost(bool, optional, tag = "4")]
    pub is_favorite: ::core::option::Option<bool>,
    /// If set, a path to an image file relative to
    /// InitializationRequest.dataRootPath that shall be used as the new room
    /// avatar. The image must remain at that path until a RoomChangeEvent
    /// changes it. After that, the callee is free to remove the file.
    /// The caller must ensure that the path is correct and that an image file is
    /// actually at that path.
    /// An empty string means that the room avatar shall be removed.
    #[prost(string, optional, tag = "5")]
    pub avatar_path: ::core::option::Option<::prost::alloc::string::String>,
}
/// Request to leave a specific room.
/// Expects a RoomLeftEvent next.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomLeaveRequest {
    /// The ID of the room that should be left.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
}
/// Event that is raised when the user has left a specific room.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomLeftEvent {
    /// The ID of the room that was left.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// The reason why the room was left.
    #[prost(enumeration = "room_left_event::RoomLeaveReason", tag = "2")]
    pub reason: i32,
    /// An optional message to be displayed to the user.
    /// This usually contains the reason why the user was kicked or banned from
    /// the room. Might be an empty string if no message is set.
    #[prost(string, optional, tag = "3")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `RoomLeftEvent`.
pub mod room_left_event {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum RoomLeaveReason {
        /// The user left the room on their own.
        User = 0,
        /// The user was kicked from the room.
        /// This might also be sent in response to a Knock request if the user
        /// was denied access to the room.
        Kicked = 1,
        /// The user was banned from the room.
        Banned = 2,
    }
    impl RoomLeaveReason {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::User => "User",
                Self::Kicked => "Kicked",
                Self::Banned => "Banned",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "User" => Some(Self::User),
                "Kicked" => Some(Self::Kicked),
                "Banned" => Some(Self::Banned),
                _ => None,
            }
        }
    }
}
/// Request to join an existing room that we can join.
/// This means that we are either invited into the room or the room is public.
/// Expects a Room message with full information about the room next, in
/// ResponseContainer.roomCreatedEvent.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomJoinRequest {
    /// The ID of the room that should be joined.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
}
/// A request to knock on a room to ask members with permission if we may join.
/// A ResponseContainer.roomCreatedEvent with full room information is expected
/// next if the request was exepted, or a RoomLeftEvent if rejected or banned
/// from the room.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomKnockRequest {
    /// The ID of the room that should be knocked.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// An optional message that should be displayed to users receiving the knock
    /// request.
    #[prost(string, optional, tag = "2")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
}
/// Request a list public rooms.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PublicRoomListRequest {
    /// The maximum number of public rooms to be returned.
    #[prost(uint32, optional, tag = "1")]
    pub limit: ::core::option::Option<u32>,
    /// A pagniation token from a previous request.
    #[prost(string, optional, tag = "2")]
    pub since: ::core::option::Option<::prost::alloc::string::String>,
    /// An optional search term to filter the rooms. Omitting it will request
    /// all public rooms.
    #[prost(string, optional, tag = "3")]
    pub generic_search_term: ::core::option::Option<::prost::alloc::string::String>,
}
/// Response to a PublicRoomListRequest.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublicRoomListResponse {
    /// The requested list of rooms.
    #[prost(message, repeated, tag = "1")]
    pub room_list: ::prost::alloc::vec::Vec<PublicRoom>,
    /// A pagination token to return the next group of rooms.
    /// Use this token in PublicRoomListRequest as the "since" token.
    #[prost(string, optional, tag = "2")]
    pub next_batch: ::core::option::Option<::prost::alloc::string::String>,
}
/// Describes a public room entity.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PublicRoom {
    /// The ID of this room.
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// The display name of the room.
    #[prost(string, optional, tag = "2")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
    /// The number of members inside this room.
    #[prost(uint32, tag = "3")]
    pub num_joined_members: u32,
    /// The topic of this room.
    #[prost(string, optional, tag = "4")]
    pub topic: ::core::option::Option<::prost::alloc::string::String>,
    /// The join rule of this room.
    #[prost(enumeration = "RoomJoinRule", tag = "5")]
    pub join_rule: i32,
}
/// Different types of cross signing verification methods.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CrossSigningMethod {
    /// A simple string.
    SasString = 0,
    /// A sequence of symbols (e.g. emojis).
    SasSymbol = 1,
}
impl CrossSigningMethod {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SasString => "SasString",
            Self::SasSymbol => "SasSymbol",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SasString" => Some(Self::SasString),
            "SasSymbol" => Some(Self::SasSymbol),
            _ => None,
        }
    }
}
/// Specifies the origin of an event (where ambiguous)
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EventOrigin {
    /// The event was user-initiated
    UserOrigin = 0,
    /// The event was initiated by the backend application
    BackendOrigin = 1,
}
impl EventOrigin {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UserOrigin => "UserOrigin",
            Self::BackendOrigin => "BackendOrigin",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UserOrigin" => Some(Self::UserOrigin),
            "BackendOrigin" => Some(Self::BackendOrigin),
            _ => None,
        }
    }
}
/// Possible states that a user can have in a room.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UserRoomState {
    Unjoined = 0,
    Joined = 1,
    Invited = 2,
    Knocked = 3,
    Banned = 4,
}
impl UserRoomState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unjoined => "Unjoined",
            Self::Joined => "Joined",
            Self::Invited => "Invited",
            Self::Knocked => "Knocked",
            Self::Banned => "Banned",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Unjoined" => Some(Self::Unjoined),
            "Joined" => Some(Self::Joined),
            "Invited" => Some(Self::Invited),
            "Knocked" => Some(Self::Knocked),
            "Banned" => Some(Self::Banned),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PresenceState {
    Unknown = 0,
    Offline = 1,
    Away = 2,
    Online = 3,
}
impl PresenceState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "Unknown",
            Self::Offline => "Offline",
            Self::Away => "Away",
            Self::Online => "Online",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Unknown" => Some(Self::Unknown),
            "Offline" => Some(Self::Offline),
            "Away" => Some(Self::Away),
            "Online" => Some(Self::Online),
            _ => None,
        }
    }
}
/// When a notification on a new message shall be created.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NotificationSetting {
    /// Notification for every message.
    AllMessages = 0,
    /// Only if the user is mentioned directly or a keyword (such as "@room") is
    /// used.
    MentionsAndKeywordsOnly = 1,
    /// No notifications for any message.
    Mute = 2,
}
impl NotificationSetting {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::AllMessages => "AllMessages",
            Self::MentionsAndKeywordsOnly => "MentionsAndKeywordsOnly",
            Self::Mute => "Mute",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AllMessages" => Some(Self::AllMessages),
            "MentionsAndKeywordsOnly" => Some(Self::MentionsAndKeywordsOnly),
            "Mute" => Some(Self::Mute),
            _ => None,
        }
    }
}
/// The order in which a sequence of messages is specified.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessagesOrder {
    /// Request messages in chronological order - latest message comes last
    Forward = 0,
    /// Request messages in anti-chronological order - latest message comes first
    Backward = 1,
}
impl MessagesOrder {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Forward => "Forward",
            Self::Backward => "Backward",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Forward" => Some(Self::Forward),
            "Backward" => Some(Self::Backward),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RoomJoinRule {
    /// A user who wishes to join the room must first receive an invite
    /// to the room from someone already inside of the room.
    Invite = 0,
    /// Users can join the room if they are invited, or they can request an
    /// invite to the room. They can be allowed or denied access.
    Knock = 1,
    /// Anyone can join the room without any prior action.
    Public = 2,
}
impl RoomJoinRule {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Invite => "Invite",
            Self::Knock => "Knock",
            Self::Public => "Public",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Invite" => Some(Self::Invite),
            "Knock" => Some(Self::Knock),
            "Public" => Some(Self::Public),
            _ => None,
        }
    }
}
